version: "3"
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:80
    env_file:
      - ../.env
    networks:
      - intelli-network

networks:
  intelli-network:
    external: true
