export const jobTitles = [
  "AI Engineer",
  "Backend Engineer",
  "Cloud Engineer",
  "Cyber Security Engineer",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "Database Analyst",
  "Devops Engineer",
  "Front end developer",
  "Full stack developer",
  "IT Specialist",
  "Java Developer",
  "Machine Learning Engineer",
  "Mobile App Developer",
  "Network Administrator",
  "Network Engineer",
  "Python Engineer",
  "Software Developer",
  "Software Engineer",
  "Support Engineer",
  "System Administrator",
  "Systems Analyst",
  "Systems Engineer",
  "UX Designer",
  "Web developer",
];
