export const languages = [
  "French",
  "Icelandic",
  "German",
  "Luxembourgish",
  "Arabic",
  "Comorian",
  "English",
  "Estonian",
  "Belarusian",
  "Russian",
  "Kinyarwanda",
  "Khmer",
  "Greek",
  "Korean",
  "Mauritian Creole",
  "Swedish",
  "Italian",
  "Maldivian",
  "Bislama",
  "Chewa",
  "Georgian",
  "Māori",
  "New Zealand Sign Language",
  "Portuguese",
  "Slovak",
  "Spanish",
  "Lao",
  "Danish",
  "Faroese",
  "Niuean",
  "Macedonian",
  "Turkish",
  "Chinese",
  "Jamaican Patois",
  "Berber",
  "Hassaniya",
  "Hiri Motu",
  "Tok Pisin",
  "Lithuanian",
  "Romanian",
  "Kyrgyz",
  "Dutch",
  "Papiamento",
  "Vietnamese",
  "Malay",
  "Swiss German",
  "Romansh",
  "Thai",
  "Uzbek",
  "Dzongkha",
  "Marshallese",
  "Norwegian Nynorsk",
  "Norwegian Bokmål",
  "Sami",
  "Hebrew",
  "Croatian",
  "Aramaic",
  "Sorani",
  "Japanese",
  "Sotho",
  "Tuvaluan",
  "Finnish",
  "Dari",
  "Pashto",
  "Turkmen",
  "Tigrinya",
  "Catalan",
  "Armenian",
  "Basque",
  "Galician",
  "Samoan",
  "Tokelauan",
  "Belizean Creole",
  "Jèrriais",
  "Tswana",
  "Manx",
  "Persian (Farsi)",
  "Greenlandic",
  "Bengali",
  "Bosnian",
  "Serbian",
  "Maltese",
  "Seychellois Creole",
  "Sinhala",
  "Tamil",
  "Guaraní",
  "Norwegian",
  "Ukrainian",
  "Urdu",
  "Slovene",
  "Chibarwe",
  "Kalanga",
  "Khoisan",
  "Ndau",
  "Northern Ndebele",
  "Shona",
  "Tonga",
  "Tsonga",
  "Venda",
  "Xhosa",
  "Zimbabwean Sign Language",
  "Swahili",
  "Cook Islands Māori",
  "Polish",
  "Czech",
  "Indonesian",
  "Aymara",
  "Quechua",
  "Sango",
  "Upper Guinea Creole",
  "Mongolian",
  "Kikongo",
  "Lingala",
  "Tshiluba",
  "Nauru",
  "Montenegrin",
  "Burmese",
  "Somali",
  "Irish",
  "Hungarian",
  "Chamorro",
  "Nepali",
  "Malagasy",
  "Kazakh",
  "Guernésiais",
  "Afrikaans",
  "Herero",
  "Khoekhoe",
  "Kwangali",
  "Lozi",
  "Ndonga",
  "Latin",
  "Albanian",
  "Haitian Creole",
  "Tongan",
  "Azerbaijani",
  "Latvian",
  "Gilbertese",
  "Amharic",
  "Palauan",
  "Fijian",
  "Fiji Hindi",
  "Norfuk",
  "Tajik",
  "Swazi",
  "Tetum",
  "Carolinian",
  "Filipino",
  "Kirundi",
  "Bulgarian",
  "Southern Ndebele",
  "Northern Sotho",
  "Southern Sotho",
  "Zulu",
  "Hindi",
].sort((a, b) => a.localeCompare(b));
